# Use a Node.js image as the base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /app/backend

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Expose any ports your backend server listens on
# EXPOSE 8080

# Command to run the backend server
CMD ["npm", "start"]
